### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#10]
Windows
Command line without prompt

**Comment by Simatwa** [comment]
Exact commands?

**Comment by johnd0e** [comment]
e.g.
```
pytgpt generate -s
```

**Comment by Simatwa** [comment]
I hope everything good now?

**Comment by johnd0e** [comment]
> I hope everything good now?

Well, taking prompt from stdin would be very useful for Windows too..

**Comment by johnd0e** [comment]
> The approach implemented seems to be limited to *nix systems.

Besides of signals usage, it is pretty the same.
And then instead of relying on `TimeoutError` we can use `sys.stdin.isatty()`.

**Comment by Simatwa** [comment]
Submit that PR folk.
