### ISSUE TITLE
Does not accept options, unless either `generate` or `interactive` explicitly specified

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#11]
E.g.
```
pytgpt -q hi
```
```
Error: No such option: -q
```

AFAIR, there was no such problem a couple of releases ago

**Comment by Simatwa** [comment]
## UPDATED README
> Starting from version 0.2.7, running `$ pytgpt` without any other command or option will automatically enter the `interactive` mode. Otherwise, you'll need to explicitly declare the desired action, for example, by running `$ pytgpt generate`.
