### ISSUE TITLE
--quiet should prevent busy-bar as well

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#12]
```
pytgpt generate -q hello>outfile
```

```
 ⣾ 
Hello! How can I assist you today? 😊                                          
```

Another minor issue: there are plenty extra spaces at the line end

**Comment by johnd0e** [comment]
It could also may sense to set "quiet" mode automatically, if output redirection detected.

**Comment by Simatwa** [comment]
> It could also may sense to set "quiet" mode automatically, if output redirection detected.

I like this idea as well.
