### ISSUE TITLE
Additional providers

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#14]
It would be nice to have also:
- [ ] gemini-pro: https://blog.google/technology/ai/google-gemini-ai/
  Official SDK: https://github.com/google/generative-ai-python
- [ ] copilot Bing: https://copilot.microsoft.com/
  Libs:
  - https://github.com/xingty/EdgeGPT
  - https://github.com/vsakkas/sydney.py
  - https://github.com/Integration-Automation/ReEdgeGPT
- [ ] copilot Github: https://github.com/features/copilot
  Sample code: https://github.com/CaoYunzhou/cocopilot-gpt
- [x] Lib: https://github.com/xtekky/gpt4free (Many subproviders)
- [ ] https://wrtn.ai/ (GPT-4, Claude 2.1 etc)
  Sample code: https://github.com/cannonLCK/wrtn_python
- [ ] Claude https://claude.ai/chats
  Libs:
  - https://github.com/KoushikNavuluri/Claude-API/pulls
  - https://github.com/st1vms/unofficial-claude2-api
  - https://github.com/duck-web-dev/claude_api
- [ ] https://huggingface.co/chat/ (Available Models: Mixtral-8x7B-Instruct-v0.1, Llama-2-70b-chat-hf, Nous-Hermes-2-Mixtral-8x7B-DPO, CodeLlama-34b-Instruct-hf, Mistral-7B-Instruct-v0.2, openchat-3.5-0106)
  Lib: https://github.com/Soulter/hugging-chat-api
- [ ] NotionAI: https://www.notion.so/product/ai
  Lib: https://github.com/vaayne/notionai-py

**Comment by Simatwa** [comment]
Could you provide links to these models.

**Comment by Simatwa** [comment]
I would like to highlight the following.

[Google's Bard](https://bard.google.com) powered by Gemini is already implemented though I'm not sure if it's pro.
[OpenAI's GPT4](https://chat.openai.com) is already implemented too. Thanks to [WebChatGPT](https://github.com/Simatwa/WebChatGPT). It's accessed slightly different  `$ pytgpt webchatgpt`

**Comment by johnd0e** [comment]
> Could you provide links to these models.

Done

> [Google's Bard](https://bard.google.com/) powered by Gemini is already implemented though I'm not sure if it's pro

Google Bard is still powered by PaLM worldwide, only in US it is by Gemini.
And current Bard support implementation is far less reliable than straightforward gemini api usage via Google SDK.

> [OpenAI's GPT4](https://chat.openai.com/) is already implemented too. Thanks to [WebChatGPT](https://github.com/Simatwa/WebChatGPT)

Well, GPT-4 via web chat is available only with Plus subscription.
But I actually mean https://github.com/xtekky/gpt4free, it is lib with many sub-providers.

**Comment by Simatwa** [comment]
Awesome.

**Comment by johnd0e** [comment]
> but one of it's major con is the dependency on Google Chrome

Most providers does not require it at all.
Some can get cookies out of it (but it is also possible to provide cookies via arguments).

**Comment by Simatwa** [comment]
And that's why we shall have to recreate them to achieve the said functionality.

**Comment by johnd0e** [comment]
https://github.com/Simatwa/python-tgpt/blob/c90c6dc3cd7e6c469ac8169526a9d527a6a7ec75/requirements.txt#L10

You probably should not fix any particular version, as `g4f` is very unstable project: frequent updates, and frequent providers changes. Yesterday some providers were ok, but today they may just gone (possibly forever).

Also consider `Status` column of this table: https://github.com/xtekky/gpt4free/tree/main?tab=readme-ov-file#-providers-and-models: there are plenty providers, but only 12 marked as `Active` at the moment.

**Comment by johnd0e** [comment]
Just updated the list (in the first post)

**Comment by sameedzahoor** [comment]
I think we should add Gemini-pro api support since it's free upto 60 requests per minute. You need an api-key which can b generated by signing into Google AI Studio. Also check this out [https://github.com/llegomark/gemini-pro-chat](url).

**Comment by Simatwa** [comment]
Okay I will look into it.

**Comment by johnd0e** [comment]
@sameedzahoor 
> I think we should add Gemini-pro api support since it's free

See https://github.com/PublicAffairs/openai-gemini

**Comment by thangckt** [comment]
> And that's why we shall have to recreate them to achieve the said functionality.

looking for this, g4f is too cumbersome and many things do not work

**Comment by BenchBadr** [comment]
Hello, I am not sure if it is the right place to ask but is there a way to use the g4f models other than the 13 first ones in the readme in python ? I can't find a way to use them along with pytgpt.

**Comment by Simatwa** [comment]
Keep it aliv

> Hello, I am not sure if it is the right place to ask but is there a way to use the g4f models other than the 13 first ones in the readme in python ? I can't find a way to use them along with pytgpt.

Try out this

```python
import pytgpt.gpt4free as gpt4free
bot = gpt4free.GPT4FREE(provider="Koala")
print(bot.chat("<Your-prompt>"))
```

**Comment by johnd0e** [comment]
More providers available via this lib: https://github.com/OE-LUCIFER/Webscout
