### ISSUE TITLE
Bard-API

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#15]
(Bard provider does not work for me, that's why am I investigating this) 

https://github.com/Simatwa/python-tgpt/blob/4eacc385443f5d7a5a6edbf14cd2e276443968f2/requirements.txt#L8
Here I wonder why version 1.4, while [latest](https://github.com/acheong08/Bard/releases) is 2.1.
And what is also important - current [GoogleBard](https://github.com/acheong08/Bard) lib in unmaintained (Public archive).

There is another package - [bardapi](https://github.com/dsdanielpark/Bard-API).
I have checked, and it is working for me, but only when I am using 3 cookies at once, like in [this](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard) example.
Just `__Secure-1PSID` is not enough.

**Comment by johnd0e** [comment]
BTW, `bardapi` it is possible not to specify cookies values explicitly, but extract them automatically from Chrome (via `browser_cookie3`)

**Comment by Simatwa** [comment]
> (Bard provider does not work for me, that's why am I investigating this)
> 
> https://github.com/Simatwa/python-tgpt/blob/4eacc385443f5d7a5a6edbf14cd2e276443968f2/requirements.txt#L8
> 
> Here I wonder why version 1.4, while [latest](https://github.com/acheong08/Bard/releases) is 2.1.
> And what is also important - current [GoogleBard](https://github.com/acheong08/Bard) lib in unmaintained (Public archive).
> 
> There is another package - [bardapi](https://github.com/dsdanielpark/Bard-API). I have checked, and it is working for me, but only when I am using 3 cookies at once, like in [this](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard) example. Just `__Secure-1PSID` is not enough.

It's only that I prioritized simplicity over functionality. Hoping to give it a fix soon.

**Comment by Simatwa** [comment]
Currently fixed. #https://github.com/Simatwa/python-tgpt/commit/b585dba9cbb1c14195109188620afe760cd822f4

**Comment by Simatwa** [comment]
Currently fixed. #https://github.com/Simatwa/python-tgpt/commit/b585dba9cbb1c14195109188620afe760cd822f4

**Comment by johnd0e** [comment]
> Currently fixed. #https://github.com/Simatwa/python-tgpt/commit/b585dba9cbb1c14195109188620afe760cd822f4

Unfortunately does not work for me.

```
ERROR : SNlM0e value not found in response. Check __Secure_1PSID value.
```
Looking through your commit I found that these 2 cookies used: `__Secure-1PSID`, `__Secure-1PAPISID`.
But for my case another cookies set required: `__Secure-1PSID`, `__Secure-1PSIDTS`, `__Secure-1PSIDCC`.

Please reopen the issue.

**Comment by johnd0e** [comment]
@Simatwa

**Comment by johnd0e** [comment]
> Have you tried with updated cookies lately?

Sure

**Comment by johnd0e** [comment]
[Cookie-Editor](https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm)

**Comment by Simatwa** [comment]
Use [export-cookie-for-puppeteer](https://github.com/ktty1220/export-cookie-for-puppeteer)

**Comment by johnd0e** [comment]
> Use [export-cookie-for-puppeteer](https://github.com/ktty1220/export-cookie-for-puppeteer)

Unfortunately no success either.
```
D:\AI\python-tgpt (main)>pygpt generate -p bard -k gemini.google.com.cookies.json
01:45:47 - ERROR : SNlM0e value not found in response. Check __Secure_1PSID value.
Quitting
```

**Comment by Simatwa** [comment]
I'm having a different error but it will be addressed in time.

```
Google Bard encountered an error:                                               
b')]}'\n\n104\n[["er",null,null,null,null,400,null,null,null,3],["di",15],["af.h
ttprm",15,"-5044462726004978363",51]]\n25\n[["e",4,null,null,140]]\n'.
```

**Comment by johnd0e** [comment]
By the way there is new implementation from g4f: https://github.com/xtekky/gpt4free/pull/1564
It works for me in gui.
But not in cli
```
pygpt generate -p Gemini Hello
16:24:13 - ERROR : Gemini does not support "stream" argument
```

**Comment by Simatwa** [comment]
Nice. Disable streaming response using flag `--whole`, shortform `-w`

**Comment by johnd0e** [comment]
Can that be done automatically?

**Comment by Simatwa** [comment]
It's very much possible but it's not implemented because of CODE INTEGRITY.

**Comment by johnd0e** [comment]
> because of CODE INTEGRITY.

What do you mean?

**Comment by piotr25691** [comment]
gemini doesn't work yet.

this is my code:

```py
import pytgpt.gemini as provider

ai = provider.GEMINI(cookie_file="gemini.cookie")
ai.chat("hi")
```

and i'm getting this error

```py
"Gemini encountered an error: [...]"
```

**Comment by johnd0e** [comment]
gemini works for me in latest release.

> Which extension did you used to export the cookies?

With both extensions is ok now.
