### ISSUE TITLE
Please provide help and user guide how to change default model

### ISSUE THREAD

**Issue by opensource-elearning** [Simatwa/python-tgpt#28]
Hi @Simatwa ,

Thank you so much for developing a great tool.

can you please add some more help on how to change the default model from CLI ?

I am mainly interested in the gpt4free usage.

**Comment by Simatwa** [comment]
Thanks for raising this concern. It will be updated asap. Meanwhile, utilize the flag `-p` or `--provider` followed by the **provider name**. 

For instance :
   ```sh
   pytgpt interactive -p Aura
   ```

> **Note** : The providers are auto-detected whether they're gf4-based or tgpt-based and then handled accordingly. 

List working g4f-based working providers:

```sh
pytgpt gpt4free list providers --working
```

For the case of tgpt-based ones, they'll be shown in the `<generate/interactive>` help info along with the `--provider` details.

```sh
pytgpt <generate/interactive> --help
```

**Comment by Simatwa** [comment]
It is very much possible to specify the model name, thanks to the `--model` flag which employs try-error mechanism to check it's validity at response generation . However, different providers support different models so  it is advisable to check the validity status of the model in relation to that particular provider. 

Perhaps you might find the following command useful.

```sh
pytgpt gpt4free list models 
```

For the case of AutoGPT, I'm yet to dig deep into it.
