### ISSUE TITLE
Can we allow to have the global setting or specific model setting along with model choice

### ISSUE THREAD

**Issue by opensource-elearning** [Simatwa/python-tgpt#30]
Hi @Simatwa ,

Just have some Ideas, if possible to implement

Can we have options to set/show the System Message, temperature, default model to set, etc. to avoid long command lines arguments

I have found one of the user interface is very easy in terms of setting the parameters and system messages usage `ollama`

Reference: https://github.com/ollama/ollama/blob/main/cmd/interactive.go#L110-L172

If we have it in pytgpt it would be great.

**Comment by Simatwa** [comment]
Nice idea folk. I think obtaining the variables from environment would be way much better.

**Comment by Simatwa** [comment]
https://github.com/Simatwa/python-tgpt#passing-environment-variables

**Comment by opensource-elearning** [comment]
Thanks for your great effort, but my Idea is slightly different.

Certainly, we can implement a mechanism within the `pytgpt` package to simplify the management of user-set parameters and store them internally in a `.env` file, eliminating the need for manual environment variable setup. This approach would make it more accessible and user-friendly for individuals with mainly non-programming backgrounds and Windows users.

Interactive Command-Line Interface (CLI)

To provide an interactive way for users to manage parameters and interact with the model, we can incorporate a command-line interface (CLI) similar to the one shown in the provided code snippet. This CLI would allow users to:

Set parameters using the `/set` command
Show model information using the `/show` command
Load or save sessions using the `/load` and `/save` commands
Exit the interactive session using the `/bye` command
Get help for commands using the `/help` command

I will request you please try [Ollama](https://github.com/ollama/ollama) once feel the experience.

**Comment by Simatwa** [comment]
Awesome. Have you tried running `h` or `help` while in **interactive** mode?

**Comment by opensource-elearning** [comment]
Without interactive i have tried `help` or `h`
