### ISSUE TITLE
Add an option to provide own system prompts in a Optimizer

### ISSUE THREAD

**Issue by piotr25691** [Simatwa/python-tgpt#32]
I’m going from `g4f` and deem this to be a better alternative, but unfortunately I couldn’t find an easy option to add my own system prompt. Could this be added?

**Comment by Simatwa** [comment]
It's already implemented. Use the flag `--intro` shortcut `-i` in CLI. For the API, make use of the parameter `intro` while instantiating the provider class to achieve the same.
