### ISSUE TITLE
More customisation for chat file intros

### ISSUE THREAD

**Issue by sameedzahoor** [Simatwa/python-tgpt#37]
Can there be a flag `--remove-intro-from-chat` which will not save the intro (or system prompt) in the .txt chat history file? That makes the chats more readable from the users perspective. We could write something like:
`pytgpt generate --intro="$intro"  --remove-intro-from-chat "Prompt"`
which would USE the intro together with the chat history but just won't write the intro to the chat history file. To continue the chat one would then have to use the `--intro` flag each time.
This has a lot of use cases if one wants dynamic intro's, we could just pass a variable `$intro` at different times when calling in an LLM on the same chat.

**Comment by Simatwa** [comment]
Okay. This will be limited to newly created chats.

**Comment by sameedzahoor** [comment]
Let's keep this issue fresh to stop it from closing again.
