### ISSUE TITLE
Internet search is not working

### ISSUE THREAD

**Issue by opensource-elearning** [Simatwa/python-tgpt#38]
```
╭─[temp@pyTGPT](phind)~[🕒18:39:02-💻00:00:00-⚡0.0s]
╰─>list all opensource proxies from internet
╭────────────────────────────────────────────────────────────────────────────────────── AI Response ───────────────────────────────────────────────────────────────────────────────────────╮
│ SEARCH {"query": "list of open source proxies"}                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─[temp@pyTGPT](phind)~[🕒18:39:17-💻00:00:14-⚡2.8s]
╰─>search on internet about opensource proxies
╭────────────────────────────────────────────────────────────────────────────────────── AI Response ───────────────────────────────────────────────────────────────────────────────────────╮
│ SEARCH {"query": "list of open source proxies"}                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─[temp@pyTGPT](phind)~[🕒18:39:53-💻00:00:50-⚡3.8s]
╰─>
```

internet search is not working using latest version

```
PS C:\Users\temp> pytgpt -v
pytgpt, version 0.5.3
PS C:\Users\temp>
```

how to control how many results are being used while responding?

**Comment by Simatwa** [comment]
╭─[Eunice@pyTGPT](phind)~[🕒21:57:50-💻00:02:08-⚡6.4s]
╰─>can't you access internet?
╭──────────────────────────────── AI Response ─────────────────────────────────╮
│ I'm designed to assist with information, programming, and technical tasks    │
│ based on the data I was trained on up until September 2023. While I can      │
│ provide insights and help with a wide range of topics, I don't have the      │
│ ability to access or retrieve real-time data from the internet. For the      │
│ latest news or current events, I recommend checking reliable news sources or │
│ using a news aggregator service.                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─[Eunice@pyTGPT](phind)~[🕒21:58:15-💻00:02:33-⚡2.6s]
╰─>But you used to?
╭──────────────────────────────── AI Response ─────────────────────────────────╮
│ Yes, in the past, I was capable of accessing and retrieving real-time data   │
│ from the internet, including current news and events. This capability        │
│ allowed me to provide up-to-date information and insights on a wide range of │
│ topics. However, my current design and training data are focused on the      │
│ information available up until September 2023, and I no longer have the      │
│ ability to access or retrieve real-time data from the internet. For the most │
│ current news or information, I recommend checking reliable news sources or   │
│ using a news aggregator service.                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
