### ISSUE TITLE
Support streaming to pipe

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#43]
**Describe the bug**
When using in terminal text streaming works as it should, but when piping output - it shows up all at once.

**To Reproduce**
```
pytgpt generate --quiet --disable-conversation "Write a short story"|less
```

**Expected behavior**
When I pipe other utilities to `less` - I see output appear line by line.

**Environment:**
- os version: Windows 10

**Comment by Simatwa** [comment]
A fix is on the way folk.

**Comment by Simatwa** [comment]
Actually am loving this idea. 

`pytgpt generate --raw "Write a short story" `

`pytgpt interactive --raw` Works fine as well. 

> `NB` : 
> There's no need for `--quiet` flag on output redirection since its set automagically.


**Kudos.**

**Comment by johnd0e** [comment]
Thank you!
