### ISSUE TITLE
Garbage "^│ {0,2}" and " *│$" at lines start-end as decoration that are interfering with copy-paste in 0.5.3!

### ISSUE THREAD

**Issue by StuDentered** [Simatwa/python-tgpt#45]
How to turn that nice box that surrounds "AI Response" off, with command-line option? It interferes greatly with code blocks manual copying, turning it into garbage!

**Comment by Simatwa** [comment]
Use the flags `-q` to disable framing and `--raw` for something related to that.

**Comment by StuDentered** [comment]
Thanks!
