### ISSUE TITLE
[BUG]: In macOS, interactive mode prompt garbles if terminal less than 130 characters wide.

### ISSUE THREAD

**Issue by StuDentered** [Simatwa/python-tgpt#48]
**Describe the bug**
in macOS, in terminals uxterm, iterm2, terminal, and many more,
prompt of command "python3 -m pytgpt interactive"
would garble if terminal if less than 130 characters wide.

**To Reproduce**
1. On macOS, Run "pip3 install python-tgpt" to install python-tgpt.
2. Open another terminal window, 130 character or wider.
3. Run "python3 -m pytgpt interactive"
4. You would see proper prompt, it would look like:
5. ╭─[User@pyTGPT](phind)~[🕒00:00:00-💻00:00:00-⚡0.0s]
   ╰─>
6. Open another terminal window, (much) less than 130 characters.
7. Run "python3 -m pytgpt interactive"
8. You would see garbled prompt, looking like:
9. <garbled prompt> "00:00:00-💻00:00:00-⚡0.0s]" <garbled prompt>
10. ╰─>
11. Note that part "00:00:00-💻00:00:00-⚡0.0s]" is exactly 31 chars long when echo'ed,
and won't garble until terminal is less than 65 characters wide.

**Expected behavior**
If terminal on macOS is less than 130 characters wide and "python3 -m pytgpt interactive" is run on it within "bash", prompt of that command would fold on itself instead of properly line breaking, as it is on other systems!

**Screenshots or Code snippets**
If applicable, add screenshots or code snippets to help explain your problem.

**Desktop (please complete the following information):**
 - OS [e.g. Windows, Mac OS, Linux]: macOS 10.12.6
 - Python-tgpt version [v0.5.3]: 0.6.3
 - Binary config [x86, x64, x32]: x64 mach-o
 - Python version [If running from source]: 3.11.6 from MacPorts

**Additional context**

**Workaround**
It is caused by mishandled color codes by faulty-compiled Python version, and, maybe, something inside "pytgpt".
Run "pytgpt" with "-nc" flag, and that issue would hide.

**Comment by Simatwa** [comment]
Could you please attach screenshot for that.
