### ISSUE TITLE
erro noo me deja mandar prompts

### ISSUE THREAD

**Issue by pipe1230321** [Simatwa/python-tgpt#51]
Submit any bug at https://github.com/Simatwa/python-tgpt/issues/new
╭─[A@pyTGPT](phind)~[🕒22:36:06-💻00:00:00-⚡0.0s]
╰─>hola 

22:36:10 - ERROR : 'choices' 
╭─[A@pyTGPT](phind)~[🕒22:36:10-💻00:00:04-⚡0.8s]
╰─>

**Comment by Simatwa** [comment]
Thank you for raising this issue. A similar one is already addressed at #50
