### ISSUE TITLE
Available voice strings

### ISSUE THREAD

**Issue by sinuso** [Simatwa/python-tgpt#52]
Hi

Is there a way to see the available voice strings used by the API?

Default is **en-US-Wavenet-C**
**es-ES-Standard-A** works but for example **es-ES-Standard-C** does not.

**Comment by Simatwa** [comment]
Yeah there is a list of supported voices. https://github.com/Simatwa/python-tgpt/blob/329ab2720676f22fb405bd419e8bf75eba45a8d9/src/pytgpt/utils.py#L706

```py
from pytgpt.utils import Audio
print(Audio.all_voices)
```

**Comment by sinuso** [comment]
> Yeah there is a list of supported voices.
> 
> https://github.com/Simatwa/python-tgpt/blob/329ab2720676f22fb405bd419e8bf75eba45a8d9/src/pytgpt/utils.py#L706
> 
> ```python
> from pytgpt.utils import Audio
> print(Audio.all_voices)
> ```

Thank you! Do you know if it is possible to add more voices?

**Comment by Simatwa** [comment]
I don't think there's a way of doing that because the voice models are setup by the host. So if it's about updating the voices, I will do so in alignment with what the host has provided.

**Comment by sinuso** [comment]
> **es-ES-Standard-A** works but for example **es-ES-Standard-C** does not.

It would be great, the **es-ES-Standard-A** voice compared to the other **es-ES-Standard-*** voices is horrible.
