### ISSUE TITLE
[BUG]: ERROR : 'async_generator' object is not iterable

### ISSUE THREAD

**Issue by RayenMnif** [Simatwa/python-tgpt#53]
while i was trying to generate an image with `pytgpt imager "<my-request>"` i got this error `ERROR : 'async_generator' object is not iterable`

 - OS: Android (termux)
 - Python-tgpt version 0.7.3
 - Python version 3.11.9

btw `python-tgpt[termux]` packages are installed as well

**Comment by Simatwa** [comment]
Thank you for raising. A fix is on the way.
