### ISSUE TITLE
[BUG]: LEO NOT WORKING

### ISSUE THREAD

**Issue by AmmuBhai22** [Simatwa/python-tgpt#54]
When using brave leo in python tgpt it gives:-

I'm unable to answer your query as your version of Brave is too out of date. Please update your browser.

**Desktop (please complete the following information):**
 - OS [Android Termux]:
 - Architecture:- [armv7i]:
 - Python version [3.11]:

Also I have tried to took only a part of leo code and this is the json I found as a result after much debugging your code:-

{"completion":"I'm unable to answer your query as your version of Brave is too out of date. Please update your browser.","stop_reason":null,"truncated":false,"stop":null,"model":"llama-2-13b-chat","log_id":"cmpl-aG244Co4GSo2br8x9kJPzz","exception":null}

**Comment by Simatwa** [comment]
As it stands we can say LEO is no longer supported. This obeys its provider's request to do so. 
Refer to https://github.com/aandrew-me/tgpt/issues/199#issuecomment-1907808474
