### ISSUE TITLE
About background of code blocks

### ISSUE THREAD

**Issue by sameedzahoor** [Simatwa/python-tgpt#8]
Is there a way to have syntax highlighting without having black background (or another theme background for that matter)? Most terminal users usually have terminal transparency enabled just for the looks of it. Perhaps there could be a flag that keeps the syntax highlighting but disables the background.

**Comment by Simatwa** [comment]
That's is an issue with how the LLM generates responses. It doesn't exclusively specify the code language required to provide syntax highlighting.

It generates something like this :

```md
``
def greet_user(name):
   print('Hello ',name)

greet_user('Example')
``
```

Instead of : 

```md
``python
def greet_user(name):
   print('Hello ',name)

greet_user('Example')
``
```

**Comment by sameedzahoor** [comment]
Can we have more themes? More dark themes actually. There is a nice theme called material. Maybe you could add it.

**Comment by Simatwa** [comment]
Is it specifically for code blocks or the whole response?

**Comment by sameedzahoor** [comment]
Code blocks mainly. 
When I keep the flag --raw on, it solves most of the problems. Code blocks still have syntax highlighting.

**Comment by Simatwa** [comment]
Unfortunately, click features only few themes for code blocks which are already implemented.
