### ISSUE TITLE
with_copied in generate mode.

### ISSUE THREAD

**Issue by sameedzahoor** [Simatwa/python-tgpt#9]
I was adding features to my script and thought it would be a nice addition to have  a `with_copied` flag for `generate` mode as well. It can go something like this,
`pytgpt generate --with-copied`.
This should pass the content of the clipboard as the prompt.
One could also have something like
`pytgpt generate --with-copied "Prompt to be appended at the end of the text from clipboard"`.
For example, if my clipboard contained a program in python we could type something like
`pytgpt generate --with-copied "Explain this code"`
and it would send the the whole thing (clipboard followed by the prompt "Explain this code") as the prompt.

**Comment by Simatwa** [comment]
Awesome.
